import { AssetType, OrderType, OrderStatus } from '@prisma/client';
import prisma from './prisma';
// In-memory list of fake orders. These objects mirror the Order model
// but are not stored in the database.
interface FakeOrder {
  id: number;
  userId: number;
  asset: AssetType;
  type: OrderType;
  amount: number;
  price: number;
  status: OrderStatus;
  createdAt: Date;
}
const fakeOrders: FakeOrder[] = [];

// In-memory list of fake trades for simulation purposes.
interface FakeTrade {
  id: number;
  asset: AssetType;
  type: OrderType;
  amount: number;
  price: number;
  createdAt: Date;
}
const fakeTrades: FakeTrade[] = [];

// List of assets that can be used for fake orders/trades. Feel free to
// adjust based on supported assets.
const assetList: AssetType[] = ['GOLD', 'USDT', 'TRX', 'USD', 'AED'];
const orderTypes: OrderType[] = ['BUY', 'SELL'];

// Utility to pick a random element from an array
function randomPick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

// Generate a random fake order and add it to the fakeOrders array.
function generateRandomFakeOrder() {
  const asset = randomPick(assetList);
  const type = randomPick(orderTypes);
  // Random amount between 0.01 and 10
  const amount = parseFloat((Math.random() * 10).toFixed(2)) + 0.01;
  // Random price between 1 and 1000 (for demonstration)
  const price = parseFloat((Math.random() * 1000).toFixed(2)) + 1;
  const id = fakeOrders.length + 1;
  fakeOrders.push({
    id,
    userId: 0, // 0 to indicate a system-generated order
    asset,
    type,
    amount,
    price,
    status: 'PENDING',
    createdAt: new Date(),
  });
}

// Generate a random fake trade and add it to the fakeTrades array. This
// simulates continuous trade activity. It does not affect the database
// or wallet balances.
function generateRandomFakeTrade() {
  const asset = randomPick(assetList);
  const type = randomPick(orderTypes);
  // Random amount between 0.01 and 5
  const amount = parseFloat((Math.random() * 5).toFixed(2)) + 0.01;
  // Random price between 1 and 1000
  const price = parseFloat((Math.random() * 1000).toFixed(2)) + 1;
  const id = fakeTrades.length + 1;
  fakeTrades.push({
    id,
    asset,
    type,
    amount,
    price,
    createdAt: new Date(),
  });
}

/**
 * Start the order book enhancer. This will populate some initial fake
 * orders and then schedule periodic generation of additional fake orders
 * and fake trades. Call this on server startup.
 */
export function startOrderBookEnhancer() {
  // Initial fake orders
  for (let i = 0; i < 5; i++) {
    generateRandomFakeOrder();
  }
  // Generate a new fake order every 15 seconds
  setInterval(generateRandomFakeOrder, 15000);
  // Generate a fake trade every 8 seconds
  setInterval(generateRandomFakeTrade, 8000);
}

/**
 * Retrieve an enhanced order book by combining real orders from the
 * database with the in-memory fake orders. Real orders with status
 * PENDING are fetched; fake orders are always considered pending.
 */
export async function getEnhancedOrderBook() {
  const realOrders = await prisma.order.findMany({ where: { status: 'PENDING' } });
  // Map real orders to include a flag if needed; here we simply return raw
  return [...realOrders, ...fakeOrders];
}

/**
 * Retrieve the list of fake trades generated by the enhancer. This can be
 * used to display simulated recent trades on the platform.
 */
export function getFakeTrades() {
  return fakeTrades;
}